### PR TITLE
Fixes bug #27

### PR DESCRIPTION
**Pull request by layflags**
Hi there, I fixed bug #27

### CODE REVIEW

**Comment by layflags** [comment]
Hi, any chance to get this released as e.g. v1.2.1 soon? The release date for my awesome AmpersandJS based widget is getting closer. Thanks!

**Comment by lukekarrys** [comment]
+1 one from me for the changes and releasing as 1.2.1. Any other @AmpersandJS/core-team want to weigh also?

**Comment by HenrikJoreteg** [comment]
+1 go ahead @lukekarrys you've got publish access already. I tend to use these to make sure we also push corresponding tags to github: https://github.com/maxogden/maintenance-modules/issues/1

**Comment by lukekarrys** [comment]
Published as `v.1.2.1

**Comment by layflags** [comment]
You made my day :-) Thx!

**Pull request merged**
